### ISSUE TITLE
Flagged as Trojan.GenericKD.72896715 virus by Bitdefender (and others)

### ISSUE THREAD

**Issue by SpaceNerd95251** [jpenilla/TabTPS#186]
**Describe the bug**
Bitdefender, along with others noticed [here](https://www.virustotal.com/gui/file/756bd86b0c4cba32f8dc448b01d5b0be113262696fee50b62c18c7cbe89874b4/detection), flag this as a virus.

**To Reproduce**
Scan with Bitdefender or any previously mentioned antivirus

**Expected behavior**
Not be flagged as a virus

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.20.1
 - Version: 1.3.18

**Comment by jpenilla** [comment]
This is very likely to be a false positive.
Currently, the build system does not create bye-for-byte reproducible artifacts, this is something I may look into fixing in the future but it would not apply to old versions.
The jar from GitHub releases which I built locally passes the scan: https://www.virustotal.com/gui/file/f1e47945c8e3c9cf65359365f3ae0885fca82c94525690eefd814ad570ec8e22
The "flagged" jar on Modrinth was built by GitHub actions and auto-published.
If you diff the jar's contents you would likely find only timestamp differences.

**Comment by Yokutto** [comment]
Sorry for pinging in a closed issue issue

I had this problem yesterday with bitdefender enterprise in our server. I have done some research and tests to know if the file could be harmful in some way, and by cutting all the details of it, I didn't have found anything for tabtps, as it pretty much a simple jar file

With that, I have sent the file as false positive for most of protection products that detected it for second opinion, and with not surprise, it got almost immediately removed from detection

This problem is sadly very common on minecraft modding community, as .jar files generally a popular language for malicious code, and in recent months it has become even common since people are mixing malicious code into popular mods and publishing to non-official mirrors (aka friend modpack through discord)

I hope this helps somehow
